### ISSUE TITLE
Add support for type parameters

### ISSUE THREAD

**Issue by LMnet** [tofu-tf/derevo#131]
Currently, there is no way to use type parameters inside `derive`:
```scala
@derive(labeled["foo"]("bar1")) // Any does not take type parameters
```
Full example: https://scastie.scala-lang.org/LMnet/GkzZYusnSvSdnrwPWCSOYQ/10

**Comment by Odomontois** [comment]
The task is actually more complex. 
To actually use it you need for derivator to fill type arguments to some typeclass as well.
So this is actually multiparameter typeclass derivation which I haven't any idea how to manage now.
I'll close for now, feel free to reopen if you'll have any ideas on implementation

**Comment by LMnet** [comment]
I thought that on the derevo level type arguments and value arguments could be handled in the almost same way. derevo just need to pass all arguments (both type and value) to a derivation function.
