### ISSUE TITLE
Add support for the Newtype library

### ISSUE THREAD

**Issue by gvolpe** [tofu-tf/derevo#56]
It seems the `@newtype` annotation from the [scala-newtype](https://github.com/estatico/scala-newtype) library doesn't work well with the `@derive` annotation. 

This fails to compile:

```scala
@newtype
@derive(show)
case class Foo(value: String)

@newtype
@derive(show)
case class Bar(value: Int)

@derive(show)
final case class Ctx(foo: Foo, bar: Bar)
```

Here's the error:

```
[error] /examples/foo.scala:19:4: magnolia: could not find Show.Typeclass for type examples..Foo
[error]     in parameter 'foo' of product type examples.Ctx
[error]   @derive(show)
[error]    ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

Maybe worth looking into [scalaz-deriving](https://github.com/scalaz/scalaz-deriving) that has support for it.

**Comment by REDNBLACK** [comment]
I’m currently in progress of making them (derevo + newtype) to work together nicely. Soon (tm)

**Comment by gvolpe** [comment]
Awesome! Thanks for your blazing fast response :smile: 

Should I close this issue or you want me to leave it open until this happens? :)

**Comment by gvolpe** [comment]
FWIW `derevo` will be featured in Chapter 10 of my book https://leanpub.com/pfp-scala :nerd_face:

**Comment by REDNBLACK** [comment]
Leave it open. btw, nice book :)

**Comment by gvolpe** [comment]
Glad to hear, thanks! :)

**Comment by rabzu** [comment]
Hi, any news on this?
